spring:
  datasource:
    url: jdbc:h2:file:~/turnos/db_archivo
    #url: jdbc:h2:file:./data/ventas
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false

