version: '3'
services:
  mysql-db:
    image: mysql:8.0.30
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: turns
      MYSQL_USER: turnos
      MYSQL_PASSWORD: turnos
      MYSQL_ROOT_PASSWORD: turnos
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my_network
  back:
    build:
     dockerfile: DockerfileBack
    container_name: back
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - my_network
  front:
    build:
     dockerfile: DockerfileFront
    container_name: front
    restart: always
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - back
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: turnos
    ports:
      - "8081:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge